{{ if .Values.btc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind-claim
  namespace: shkeeper
spec:
  volumeClaimTemplates:
    spec:
      storageClassName: {{ .Values.storageClassName }}
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: 15Gi
{{ end }}