apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shkeeper-db-claim
  namespace: shkeeper
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

