apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shkeeper-claim
  namespace: shkeeper
spec:
  volumeClaimTemplates:
    spec:
      storageClassName: {{ .Values.storageClassName }}
      accessModes: 
        - "ReadWriteMany"
      resources:
        requests:
          storage: 10Gi

