{{ if .Values.btc.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bitcoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{ if .Values.ltc.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: litecoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{ if .Values.doge.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dogecoin-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}
{{ if .Values.usdt.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: usdt-rpc
  namespace: shkeeper
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
data:
  username: Yml0Y29pbmQtdXNlcg==
{{ end }}